# Site settings
title: Freesound Labs
email: freesound@freesound.org
description: > # this means to ignore newlines until "baseurl:"
  Freesound Labs is a directory of projects, hacks, apps, research and other 
  initiatives that use content from Freesound or use the Freesound API. This 
  site is run by the Freesound Team at the Music Technology Group of Universitat 
  Pompeu Fabra.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://labs.freesound.org" # the base hostname & protocol for your site
permalink: /:categories/:title.html
paginate: 5

# Build settings
markdown: kramdown